CREATE OR REPLACE TABLE PatientRec (
PATIENTID NUMBER,
NAME VARCHAR,
DIAGNOSIS VARCHAR,
ADMISSIONDATE DATE
);

INSERT INTO PatientRec VALUES
(1, 'Alice', 'Flu', '2024-11-01'),
(2, 'Bob', 'Cold', '2024-11-02'),
(3, 'Charlie', 'Asthma', '2024-11-03');



UPDATE PatientRec SET DIAGNOSIS = 'PNEUMONIA' WHERE PATIENTID = 1;

CREATE OR REPLACE TABLE PatientRecSCLONE CLONE PatientRec AT(OFFSET=>-50);

SELECT * FROM PatientRec;

SELECT * FROM PatientRecSCLONE;